---
title: "Nimble Attempt 1"
author: "Ben Weinstein"
date: "June 27, 2016"
output: html_document
---

```{r,eval=T}
#Load in data from Observed2m_Generate.Rmd
load("C:/Users/Ben/Documents/NetworkPredict/Observed.RData")
```

Here is the data
```{r}
head(indat)
```


#Hierarchical Occupancy Model

For hummingbird species i feeding on plant species j observed at time k and sampling event observed by transect (YTransect) or camera (YCamera)

Observation Model:

$$ YTransect_{i,j,k,d} \sim Bernoulli(\omega_{Transect}) $$
$$ YCamera_{i,j,k,d} \sim Bernoulli(\omega_{Camera}) $$
$$ \omega_{Camera} <- \phi_{Camera} * EffortCamera_k $$
$$ \omega_{Transect} <- \phi_{Transect}* EffortTransect_k $$

Process Model:

$$ p_{i,j,k} \sim Bernoulli(\rho_{i,j,k}) $$
$$ logit(\rho_{i,j,k}) = \alpha_i + \beta_{1,i} * Traitmatch_{i,j} + \beta_{2,i} *Resources_k + \beta_{3,i} * Traitmatch_{i,j} * Resources_k $$

**Priors**

$$ \phi_{Camera} \sim U(0,1) $$
$$ \phi_{Transect} \sim U(0,1) $$
$$\alpha_i \sim Normal(\alpha_\mu,\alpha_\tau)$$
$$\beta_{1,i} \sim Normal(\mu_{\beta_1,\tau_{beta_1}})$$
$$\beta_{2,i} \sim Normal(\mu_{\beta_2,\tau_{beta_2}})$$
$$\beta_{3,i} \sim Normal(\mu_{\beta_3,\tau_{beta_3}})$$

Group Level Means
$$ \mu_\alpha \sim Normal(0,0.0001)$$
$$\mu_{\beta_1} \sim Normal(0,0.0001)$$
$$\mu_{\beta_2} \sim Normal(0,0.0001)$$
$$\mu_{\beta_3} \sim Normal(0,0.0001)$$

Group Level Variance
$$\tau_{\alpha} \sim Uniform(0,1000)$$
$$\tau_{\beta_1} \sim Uniform(0,1000)$$
$$\tau_{\beta_2} \sim Uniform(0,1000)$$
$$\tau_{\beta_3} \sim Uniform(0,1000)$$


```{r,eval=T,error=TRUE}
m<-nimble::nimbleModel(code=
                        quote({
                          
    #Compute true state for each pair of birds and plants
    for (i in 1:Birds){
    for (j in 1:Plants){
    for (k in 1:Times){
    
    #Process Model
    logit(rho[i,j,k])<-alpha[i] + beta1[i] * Traitmatch[i,j] + beta2[i] * resources[i,j,k] + beta3[i] * resources[i,j,k] * Traitmatch[i,j]
    
    #True State
    S[i,j,k] ~ dbern(rho[i,j,k])
    }
    }
    }
    
    #Observation Model
    for (x in 1:Nobs){
    
    #Observation Process for cameras
    detect_cam[x]<-dcam[Bird[x]] * cam_surveys[x]

    #Observation Process for transects
    detect_transect[x]<-dtrans[Bird[x]] * trans_surveys[x]

    Yobs_camera[x] ~ dbern(detect_cam[x] * S[Bird[x],Plant[x],Time[x]])    
    Yobs_transect[x] ~ dbern(detect_transect[x] * S[Bird[x],Plant[x],Time[x]])    

    }

    #Priors
    #Observation model
    #Detect priors, logit transformed - Following lunn 2012 p85
    
    for(x in 1:Birds){
      #For Cameras
      dcam[x] ~ dnorm(dprior_cam,tau_dcam)
  
      #For Transects
      dtrans[x] ~ dnorm(dprior_trans,tau_dtrans)
    }
    
    #Detection group prior
    dprior_cam ~ dnorm(0,0.386)
    dprior_trans ~ dnorm(0,0.386)
    
    #Group effect detect camera
    tau_dcam ~ dunif(0,1000)
    sigma_dcam<-pow(1/tau_dcam,.5)
    
    #Group effect detect camera
    tau_dtrans ~ dunif(0,1000)
    sigma_dtrans<-pow(1/tau_dtrans,.5)

    #Process Model
    #Species level priors
    for (i in 1:Birds){
      
      #Intercept
      #logit prior, then transform for plotting
      alpha[i] ~ dnorm(alpha_mu,alpha_tau)

      #Traits slope 
      beta1[i] ~ dnorm(beta1_mu,beta1_tau)    

      #Plant slope
      beta2[i] ~ dnorm(beta2_mu,beta2_tau)    
      
      #Interaction slope
      beta3[i] ~ dnorm(beta3_mu,beta3_tau)    
    }

    #Group process priors

    #Intercept 
    alpha_mu ~ dnorm(0,0.386)
    alpha_tau ~ dunif(0,1000)
    alpha_sigma<-pow(1/alpha_tau,0.5) 
    
    #Trait
    beta1_mu~dnorm(0,0.386)
    beta1_tau ~ dunif(0,1000)
    beta1_sigma<-pow(1/beta1_tau,0.5)
    
    #Resources
    beta2_mu~dnorm(0,0.386)
    beta2_tau ~ dunif(0,1000)
    beta2_sigma<-pow(1/beta2_tau,0.5)

    #Interaction
    beta3_mu~dnorm(0,0.386)
    beta3_tau ~ dunif(0,1000)
    beta3_sigma<-pow(1/beta3_tau,0.5)

                         })
,constants=list(Birds=Birds,
                Plants=Plants,
                Times=Times,
                Bird=1:Birds,
                Plant=1:Plants,
                Time=1:Times,
                Nobs=nrow(indat),
                Bird=indat$jBird,
                Time=indat$jTime,
                Plant=indat$jPlant),
  data
    =list(
    Yobs_camera = indat$Camera,
    Yobs_transect = indat$Transect,
    resources=resourceMatrix,
    cam_surveys= (indat$Survey_Type=="Camera")*1,
    trans_surveys= (indat$Survey_Type=="Transect")*1,
    Traitmatch=jTraitmatch))

```
